# SPDX-License-Identifier: Apache-2.0

# This list is generated, it contains all python scripts that existed before ruff was introduced,
# remove entries for files that pass CI compliance testing.

[lint.per-file-ignores]
"./scripts/ci/check_compliance.py" = [
    "B904",     # https://docs.astral.sh/ruff/rules/raise-without-from-inside-except
    "E501",     # https://docs.astral.sh/ruff/rules/line-too-long
    "E741",     # https://docs.astral.sh/ruff/rules/ambiguous-variable-name
    "F401",     # https://docs.astral.sh/ruff/rules/unused-import
    "I001",     # https://docs.astral.sh/ruff/rules/unsorted-imports
    "SIM112",   # https://docs.astral.sh/ruff/rules/uncapitalized-environment-variables
    "SIM116",   # https://docs.astral.sh/ruff/rules/if-else-block-instead-of-dict-lookup
    "UP015",    # https://docs.astral.sh/ruff/rules/redundant-open-modes
]
"./scripts/gitlint/zephyr_commit_rules.py" = [
    "E501",     # https://docs.astral.sh/ruff/rules/line-too-long
    "I001",     # https://docs.astral.sh/ruff/rules/unsorted-imports
    "UP030",    # https://docs.astral.sh/ruff/rules/format-literals
    "UP032",    # https://docs.astral.sh/ruff/rules/f-string
]
"./scripts/pylint/checkers/argparse-checker.py" = [
    "F821",     # https://docs.astral.sh/ruff/rules/undefined-name
    "I001",     # https://docs.astral.sh/ruff/rules/unsorted-imports
]

[format]
exclude = [
    "./doc/bridle/conf.py",
    "./doc/devicetree/conf.py",
    "./doc/_extensions/bridle/api_overview.py",
    "./doc/_extensions/bridle/__init__.py",
    "./doc/_extensions/bridle/inventory_builder.py",
    "./doc/_extensions/bridle/link-roles.py",
    "./doc/_extensions/bridle/manifest_projects_table.py",
    "./doc/_extensions/bridle/options_from_kconfig.py",
    "./doc/_extensions/bridle/table_from_rows.py",
    "./doc/_extensions/bridle/warnings_filter.py",
    "./doc/_extensions/tsn_include/__init__.py",
    "./doc/_extensions/tsn_include/tsn_include.py",
    "./doc/kconfig/conf.py",
    "./doc/_scripts/merge_search_indexes.py",
    "./doc/_utils/utils.py",
    "./doc/zephyr/conf.py",
    "./samples/helloshell/pytest/test_shell.py",
    "./scripts/ci/check_compliance.py",
    "./scripts/gitlint/zephyr_commit_rules.py",
    "./scripts/pylint/checkers/argparse-checker.py",
    "./scripts/west_commands/export.py",
    "./scripts/west_commands/zephyr_trampoline.py",
]
