[manifest]
group-filter = ["-babblesim"]

[[manifest.projects]]
name = "ubxlib"
url = "https://github.com/tiacsys/ubxlib"
revision = "62c0021cbf079b43cdd9a219e9b10b49ea616e19"
path = "modules/lib/ubxlib"
submodules = true

[manifest.projects.nix]
hash = "sha256-2GXfsdjqouRrOKJg+1dCTZikS4oi8WPoe6xbAKU+Wv8="

[[manifest.projects]]
name = "zephyr"
url = "https://github.com/tiacsys/zephyr"
revision = "56161537ac3aa20d71925b4cd59231615e655eb0"
clone-depth = 5000
west-commands = "scripts/west-commands.yml"

[manifest.projects.userdata]
west-commands-path = "scripts/west_commands"

[manifest.projects.nix]
hash = "sha256-oC28viN3s9O+BXQUONU5dDxuS3WZRLF7sYvZ12Qhfgs="

[[manifest.projects]]
name = "canopennode"
url = "https://github.com/zephyrproject-rtos/canopennode"
revision = "dec12fa3f0d790cafa8414a4c2930ea71ab72ffd"
path = "modules/lib/canopennode"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-BbmEjeMzKznRDx329PIkmPMCGI+du6wiOj+3X7Ap1HQ="

[[manifest.projects]]
name = "chre"
url = "https://github.com/zephyrproject-rtos/chre"
revision = "3b32c76efee705af146124fb4190f71be5a4e36e"
path = "modules/lib/chre"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-7SdP9zSKZ+6s+nkIcIbjZSnacq2/t06DiR2gcaL07T4="

[[manifest.projects]]
name = "psa-arch-tests"
url = "https://github.com/zephyrproject-rtos/psa-arch-tests"
revision = "2cadb02a72eacda7042505dcbdd492371e8ce024"
path = "modules/tee/tf-m/psa-arch-tests"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-TVVfNZyRrval2wvvu9DSIxhB2OiyFPSZRX2lsdcFcoA="

[[manifest.projects]]
name = "tf-m-tests"
url = "https://github.com/zephyrproject-rtos/tf-m-tests"
revision = "c712761dd5391bf3f38033643d28a736cae89a19"
path = "modules/tee/tf-m/tf-m-tests"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-KbkVSwyw/g8MzTrwHjraRg5yQ3AaTZYW67H0AJPUeGU="

[[manifest.projects]]
name = "acpica"
url = "https://github.com/zephyrproject-rtos/acpica"
revision = "8d24867bc9c9d81c81eeac59391cda59333affd4"
path = "modules/lib/acpica"

[manifest.projects.nix]
hash = "sha256-DwE7etw6DqWHb/NvGwep19RYsVmA/CBxvTnFVmqf2Io="

[[manifest.projects]]
name = "cmsis"
url = "https://github.com/zephyrproject-rtos/cmsis"
revision = "512cc7e895e8491696b61f7ba8066b4a182569b8"
path = "modules/hal/cmsis"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-IR4Za8TuYY7nkqK57xUJ2uWnCp7wB9B4/ZjhalLhCUU="

[[manifest.projects]]
name = "cmsis_6"
url = "https://github.com/zephyrproject-rtos/CMSIS_6"
revision = "6dd50439a9b83398ff2ae1376eef0a2a0b95913b"
path = "modules/hal/cmsis_6"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-NaQ/2ko3xDqd5sPFAV/QB5WbHKscx1x0UB4WsYB5ppU="

[[manifest.projects]]
name = "edtt"
url = "https://github.com/zephyrproject-rtos/edtt"
revision = "b9ca3c7030518f07b7937dacf970d37a47865a76"
path = "tools/edtt"
groups = ["tools"]

[manifest.projects.nix]
hash = "sha256-wY2DmLk4TO2Q6pvKb3iBlRm9ShUd9ePxtPr9eJkSS5g="

[[manifest.projects]]
name = "fatfs"
url = "https://github.com/zephyrproject-rtos/fatfs"
revision = "16245c7c41d2b79e74984f49b5202551786b8a9b"
path = "modules/fs/fatfs"
groups = ["fs"]

[manifest.projects.nix]
hash = "sha256-pHr2E+ty2fEMrGpCBa/yVQpNEgBFV3brNmGXOZBPc5g="

[[manifest.projects]]
name = "hal_adi"
url = "https://github.com/zephyrproject-rtos/hal_adi"
revision = "f8f65473168a4e9f71f20c0c5387f6b80fe54cf3"
path = "modules/hal/adi"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-C1hg0xTg/kX1m++8Pr0VXJyfvnbYR/3+4qmkkamwEas="

[[manifest.projects]]
name = "hal_ambiq"
url = "https://github.com/zephyrproject-rtos/hal_ambiq"
revision = "f46941f3427bbc05d893a601660e6e3cffe9e29d"
path = "modules/hal/ambiq"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-wDOkEnBHNLtcd2GQKyouTgB4yiqShT/cCvBTF4MVNow="

[[manifest.projects]]
name = "hal_atmel"
url = "https://github.com/zephyrproject-rtos/hal_atmel"
revision = "ca7e4c6920f44b9d677ed5995ffa169f18a54cdf"
path = "modules/hal/atmel"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-VO7zdFW6qaYgS3I0AjNOv7LYQiR8KuH91GeLjxMr/4s="

[[manifest.projects]]
name = "hal_bouffalolab"
url = "https://github.com/zephyrproject-rtos/hal_bouffalolab"
revision = "5811738e2be348f30dc97d78280f2735d5d14084"
path = "modules/hal/bouffalolab"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-uFOEHWBtMj3rm9IOmURXkC77xL7SmOLfi8vZxyKJVLg="

[[manifest.projects]]
name = "hal_espressif"
url = "https://github.com/zephyrproject-rtos/hal_espressif"
revision = "82c93ea7f5e90f7e028dc59bfa351d774eb66f37"
path = "modules/hal/espressif"
west-commands = "west/west-commands.yml"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-/vtTze0+WkHCqLTZxD3QXSiOTGeJ8LeVyChznnEPIKs="

[[manifest.projects]]
name = "hal_ethos_u"
url = "https://github.com/zephyrproject-rtos/hal_ethos_u"
revision = "50ddffca1cc700112f25ad9bc077915a0355ee5d"
path = "modules/hal/ethos_u"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-+J+bR7GJmZMi026RPE2rgYRb1SSzVnCBLNxR+9Tqx+0="

[[manifest.projects]]
name = "hal_gigadevice"
url = "https://github.com/zephyrproject-rtos/hal_gigadevice"
revision = "2994b7dde8b0b0fa9b9c0ccb13474b6a486cddc3"
path = "modules/hal/gigadevice"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-Cgcc+7tJy0ryQG4ynrlv7OmNe3OW2kMx1mStGROgA5o="

[[manifest.projects]]
name = "hal_infineon"
url = "https://github.com/zephyrproject-rtos/hal_infineon"
revision = "0fe4f3aee9c8f7002996a94d91299b2c28d6a8fa"
path = "modules/hal/infineon"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-ULw4BzNOjqr6ZCwugbtG7hZQh4InPcpTb7MIOvJaGW4="

[[manifest.projects]]
name = "hal_intel"
url = "https://github.com/zephyrproject-rtos/hal_intel"
revision = "0447cd22e74d7ca243653f21cfd6e38c016630c6"
path = "modules/hal/intel"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-HEgoY3jABEZRGL1GCT2CiCroZduaZTuiVyYO4fqozU0="

[[manifest.projects]]
name = "hal_microchip"
url = "https://github.com/zephyrproject-rtos/hal_microchip"
revision = "4b74f4081342423badcf758278bbc0582ca8735d"
path = "modules/hal/microchip"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-Q5aaXGi0yUzqdt1XpkoqDRlmdT7ruFa2HPx97Cpd0k0="

[[manifest.projects]]
name = "hal_nordic"
url = "https://github.com/zephyrproject-rtos/hal_nordic"
revision = "6e39d4f2b078afaebdb84875089486152fcacb9c"
path = "modules/hal/nordic"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-cYjpaUqfbGOmZVoY4gecKLxBw0MfoDZHkZbGz9mpsZ4="

[[manifest.projects]]
name = "hal_nuvoton"
url = "https://github.com/zephyrproject-rtos/hal_nuvoton"
revision = "be1042dc8a96ebe9ea4c5d714f07c617539106d6"
path = "modules/hal/nuvoton"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-fIeEx2SzZl9lrx/FoxBO3XsqdbqjRZAzJA9YBho6cK0="

[[manifest.projects]]
name = "hal_nxp"
url = "https://github.com/zephyrproject-rtos/hal_nxp"
revision = "ad531e7b9980b171f90c651340bb1bb6cc2c6d51"
path = "modules/hal/nxp"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-QemS/7C4caLxgCwrf3X9lL/7d7OYrN4mcXn39kLQraE="

[[manifest.projects]]
name = "hal_openisa"
url = "https://github.com/zephyrproject-rtos/hal_openisa"
revision = "eabd530a64d71de91d907bad257cd61aacf607bc"
path = "modules/hal/openisa"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-krI/9sr57ZjerDKb9lQvIOD+q6vfiXqRGqV7cbW9Bqs="

[[manifest.projects]]
name = "hal_quicklogic"
url = "https://github.com/zephyrproject-rtos/hal_quicklogic"
revision = "bad894440fe72c814864798c8e3a76d13edffb6c"
path = "modules/hal/quicklogic"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-EFeySS+Kz7RecJ7it5CVAdP0y9m2gCCGl0Pu6l21+TQ="

[[manifest.projects]]
name = "hal_renesas"
url = "https://github.com/zephyrproject-rtos/hal_renesas"
revision = "9b99067e29a1b44b53192c2c797db330f5703462"
path = "modules/hal/renesas"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-+QPLx1eplSQgtI6WSEzqCNC6/yn1V4o+A1m6uAFNZBE="

[[manifest.projects]]
name = "hal_rpi_pico"
url = "https://github.com/zephyrproject-rtos/hal_rpi_pico"
revision = "7b57b24588797e6e7bf18b6bda168e6b96374264"
path = "modules/hal/rpi_pico"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-jpEq/h/ec3cCH0ZZK4OTs+zx9V+g4Sg05HF5uDbwmI8="

[[manifest.projects]]
name = "hal_silabs"
url = "https://github.com/zephyrproject-rtos/hal_silabs"
revision = "411072b67f564eb6ebceadbf9ffb1bb1ccdc7e73"
path = "modules/hal/silabs"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-93UWICiIExXvHgKt289kZkrO6l8JtUoDT40N08fdwIE="

[[manifest.projects]]
name = "hal_st"
url = "https://github.com/zephyrproject-rtos/hal_st"
revision = "9f81b4427e955885398805b7bca0da3a8cd9109c"
path = "modules/hal/st"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-kpV0PCBd96ZbmKoLZtjrd0JovJK3++w56JdY0u7FP0Q="

[[manifest.projects]]
name = "hal_stm32"
url = "https://github.com/zephyrproject-rtos/hal_stm32"
revision = "90f56420db7b2567675f623af09c474eae410814"
path = "modules/hal/stm32"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-dPVqLKVJWDHI0lsbZ1SoWVK6+UntLPPW81JRu7eZU8U="

[[manifest.projects]]
name = "hal_tdk"
url = "https://github.com/zephyrproject-rtos/hal_tdk"
revision = "6727477af1e46fa43878102489b9672a9d24e39f"
path = "modules/hal/tdk"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-VJ+M9WD9FPfGmKfxI+uBIaLfPcADMtXaS5paQ67UjY0="

[[manifest.projects]]
name = "hal_telink"
url = "https://github.com/zephyrproject-rtos/hal_telink"
revision = "4226c7fc17d5a34e557d026d428fc766191a0800"
path = "modules/hal/telink"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-6KopXpZXOK7v5AEbLPHUuxWya0eXTvDcDRDzqlejzoo="

[[manifest.projects]]
name = "hal_ti"
url = "https://github.com/zephyrproject-rtos/hal_ti"
revision = "bc8e7b99bb668cc51a3aa384448a48c48a33f8e2"
path = "modules/hal/ti"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-VVw9QbT3wrlhjQJa8m/eEn/7jY1iliVNvAMdlEwB/Aw="

[[manifest.projects]]
name = "hal_wurthelektronik"
url = "https://github.com/zephyrproject-rtos/hal_wurthelektronik"
revision = "e3e2797b224fc48fdef1bc3e5a12a7c73108bba2"
path = "modules/hal/wurthelektronik"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-Xf/xazKK3ttGV7hdvUQanust2AUGjDyt62h1yl1Sc7A="

[[manifest.projects]]
name = "hal_xtensa"
url = "https://github.com/zephyrproject-rtos/hal_xtensa"
revision = "b38620c7cc61e349e192ed86a54940a5cd0636b7"
path = "modules/hal/xtensa"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-T2XCyXF3hGy9spIMAPebsoTwl4WkzJFZZMHy2KDCYq8="

[[manifest.projects]]
name = "liblc3"
url = "https://github.com/zephyrproject-rtos/liblc3"
revision = "48bbd3eacd36e99a57317a0a4867002e0b09e183"
path = "modules/lib/liblc3"

[manifest.projects.nix]
hash = "sha256-OWuj68+YztIh/dPvwqjW7ch7Ph3aiEIDvO9rMkVIrQ8="

[[manifest.projects]]
name = "libmetal"
url = "https://github.com/zephyrproject-rtos/libmetal"
revision = "91d38634d1882f0a2151966f8c5c230ce1c0de7b"
path = "modules/hal/libmetal"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-xaX5Dp9Vj8ovvHYf6c439WXOflji6J9GtCNGbGeh6Tk="

[[manifest.projects]]
name = "littlefs"
url = "https://github.com/zephyrproject-rtos/littlefs"
revision = "8f5ca347843363882619d8f96c00d8dbd88a8e79"
path = "modules/fs/littlefs"
groups = ["fs"]

[manifest.projects.nix]
hash = "sha256-MuXfpmEE3z0ZOtfjp93aAh/7xZhShmHzwHC5nyN2QQg="

[[manifest.projects]]
name = "loramac-node"
url = "https://github.com/zephyrproject-rtos/loramac-node"
revision = "fb00b383072518c918e2258b0916c996f2d4eebe"
path = "modules/lib/loramac-node"

[manifest.projects.nix]
hash = "sha256-t6CRkm5TheFvUuc+Qj3JaveWYOaHRH6Pquvlb5YlsOg="

[[manifest.projects]]
name = "lvgl"
url = "https://github.com/zephyrproject-rtos/lvgl"
revision = "b03edc8e6282a963cd312cd0b409eb5ce263ea75"
path = "modules/lib/gui/lvgl"

[manifest.projects.nix]
hash = "sha256-akmYjcyRikKxG9W37u+3aal+BbeBltbprmCxkzGAPp4="

[[manifest.projects]]
name = "mbedtls"
url = "https://github.com/zephyrproject-rtos/mbedtls"
revision = "5f889934359deccf421554c7045a8381ef75298f"
path = "modules/crypto/mbedtls"
groups = ["crypto"]

[manifest.projects.nix]
hash = "sha256-RYoQuBokTrN82BJP+yxcwGud+T9WfN1aZURI4pKtzYM="

[[manifest.projects]]
name = "mcuboot"
url = "https://github.com/zephyrproject-rtos/mcuboot"
revision = "990b1fcb367e27056b282f183e819964fdbfe907"
path = "bootloader/mcuboot"
groups = ["bootloader"]

[manifest.projects.nix]
hash = "sha256-F+iMJ42Cbprlw9ZxJNMHOTosWAlXZNpxlrudYp0/zUs="

[[manifest.projects]]
name = "mipi-sys-t"
url = "https://github.com/zephyrproject-rtos/mipi-sys-t"
revision = "33e5c23cbedda5ba12dbe50c4baefb362a791001"
path = "modules/debug/mipi-sys-t"
groups = ["debug"]

[manifest.projects.nix]
hash = "sha256-rDsj8ZnJIfNaAhrjnx69U0nYVY9T5x5kmMsmFgn3wPA="

[[manifest.projects]]
name = "net-tools"
url = "https://github.com/zephyrproject-rtos/net-tools"
revision = "986bfeb040df3d9029366de8aea4ce1f84e93780"
path = "tools/net-tools"
groups = ["tools"]

[manifest.projects.nix]
hash = "sha256-XgL/LuMV4OVlSX8afa4K1r4En2vruzkvQXBH5zSH7dc="

[[manifest.projects]]
name = "open-amp"
url = "https://github.com/zephyrproject-rtos/open-amp"
revision = "c30a6d8b92fcebdb797fc1a7698e8729e250f637"
path = "modules/lib/open-amp"

[manifest.projects.nix]
hash = "sha256-WRYNd848wZNb8EfM+XbLb0vqwpK6hncJK7Q29HbU6Co="

[[manifest.projects]]
name = "openthread"
url = "https://github.com/zephyrproject-rtos/openthread"
revision = "3ae741f95e7dfb391dec35c48742862049eb62e8"
path = "modules/lib/openthread"

[manifest.projects.nix]
hash = "sha256-tmSsRJlMzh/BIdejsgy+EJqAlQxCxsKbm0DLV8tYc3A="

[[manifest.projects]]
name = "picolibc"
url = "https://github.com/zephyrproject-rtos/picolibc"
revision = "560946f26db075c296beea5b39d99e6de43c9010"
path = "modules/lib/picolibc"

[manifest.projects.nix]
hash = "sha256-22aCOAjDfEFtlUX3VCpsa/7VGYjObpYn7EkcyYnj/fg="

[[manifest.projects]]
name = "segger"
url = "https://github.com/zephyrproject-rtos/segger"
revision = "cf56b1d9c80f81a26e2ac5727c9cf177116a4692"
path = "modules/debug/segger"
groups = ["debug"]

[manifest.projects.nix]
hash = "sha256-RiQm92YGm+pZPLDcZxI9brNfIerumduLFNi6JKGj99E="

[[manifest.projects]]
name = "tinycrypt"
url = "https://github.com/zephyrproject-rtos/tinycrypt"
revision = "1012a3ebee18c15ede5efc8332ee2fc37817670f"
path = "modules/crypto/tinycrypt"
groups = ["crypto"]

[manifest.projects.nix]
hash = "sha256-JQmkN+ircGU5Ald1+Q4lysuxhZLg2mJpNQ92+agMoCQ="

[[manifest.projects]]
name = "trusted-firmware-a"
url = "https://github.com/zephyrproject-rtos/trusted-firmware-a"
revision = "713ffbf96c5bcbdeab757423f10f73eb304eff07"
path = "modules/tee/tf-a/trusted-firmware-a"
groups = ["tee"]

[manifest.projects.nix]
hash = "sha256-Dx+/fBHS7LabDu8mzfewdLdhoxVl5NO271V2EJZ+Y7g="

[[manifest.projects]]
name = "trusted-firmware-m"
url = "https://github.com/zephyrproject-rtos/trusted-firmware-m"
revision = "c150f48855f04d77451a39bfaa80d14eb61d918b"
path = "modules/tee/tf-m/trusted-firmware-m"
groups = ["tee"]

[manifest.projects.nix]
hash = "sha256-76o6C9iSs3BCHlXo9mdZbRY5rIgJHE11uV4bsArY/4g="

[manifest.self]
path = "bridle"
west-commands = "scripts/west-commands.yml"
