[manifest]
group-filter = ["-babblesim"]

[[manifest.projects]]
name = "ubxlib"
url = "https://github.com/tiacsys/ubxlib"
revision = "9e2b5b10d78b86a96429996aa8a6c2c91ecf0cb7"
path = "modules/lib/ubxlib"

[manifest.projects.nix]
hash = "sha256-BskxisDfK5rCG8YIRGeQrEX6Hl7dhuh3X/dzj0bLumg="

[[manifest.projects]]
name = "zephyr"
url = "https://github.com/tiacsys/zephyr"
revision = "fcbbd168062d01959635977f3fb051be167ae0f3"
clone-depth = 5000
west-commands = "scripts/west-commands.yml"

[manifest.projects.userdata]
west-commands-path = "scripts/west_commands"

[manifest.projects.nix]
hash = "sha256-kFpd6wP9IRRJxJSWI0mGlYINAG10kN0mvIGn+UCsB6M="

[[manifest.projects]]
name = "canopennode"
url = "https://github.com/zephyrproject-rtos/canopennode"
revision = "dec12fa3f0d790cafa8414a4c2930ea71ab72ffd"
path = "modules/lib/canopennode"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-BbmEjeMzKznRDx329PIkmPMCGI+du6wiOj+3X7Ap1HQ="

[[manifest.projects]]
name = "chre"
url = "https://github.com/zephyrproject-rtos/chre"
revision = "3b32c76efee705af146124fb4190f71be5a4e36e"
path = "modules/lib/chre"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-7SdP9zSKZ+6s+nkIcIbjZSnacq2/t06DiR2gcaL07T4="

[[manifest.projects]]
name = "psa-arch-tests"
url = "https://github.com/zephyrproject-rtos/psa-arch-tests"
revision = "2cadb02a72eacda7042505dcbdd492371e8ce024"
path = "modules/tee/tf-m/psa-arch-tests"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-oYpqLIbtKsNHQ9FQjhSM8Rvd/VM4M+ETO5hum2fZVq8="

[[manifest.projects]]
name = "tf-m-tests"
url = "https://github.com/zephyrproject-rtos/tf-m-tests"
revision = "d552e4f18b92032bd335d5e3aa312f6acd82a83b"
path = "modules/tee/tf-m/tf-m-tests"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-UUy4OJeOp0fbXVV+w/ypDZPFDVk13MSyeaTqMOHZh7g="

[[manifest.projects]]
name = "acpica"
url = "https://github.com/zephyrproject-rtos/acpica"
revision = "8d24867bc9c9d81c81eeac59391cda59333affd4"
path = "modules/lib/acpica"

[manifest.projects.nix]
hash = "sha256-DwE7etw6DqWHb/NvGwep19RYsVmA/CBxvTnFVmqf2Io="

[[manifest.projects]]
name = "cmsis"
url = "https://github.com/zephyrproject-rtos/cmsis"
revision = "4b96cbb174678dcd3ca86e11e1f24bc5f8726da0"
path = "modules/hal/cmsis"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-vzCbE69wCMLIjrSz1m8yspgVCto4JSm4Qg5zY/Ozg+k="

[[manifest.projects]]
name = "edtt"
url = "https://github.com/zephyrproject-rtos/edtt"
revision = "b9ca3c7030518f07b7937dacf970d37a47865a76"
path = "tools/edtt"
groups = ["tools"]

[manifest.projects.nix]
hash = "sha256-wY2DmLk4TO2Q6pvKb3iBlRm9ShUd9ePxtPr9eJkSS5g="

[[manifest.projects]]
name = "fatfs"
url = "https://github.com/zephyrproject-rtos/fatfs"
revision = "427159bf95ea49b7680facffaa29ad506b42709b"
path = "modules/fs/fatfs"
groups = ["fs"]

[manifest.projects.nix]
hash = "sha256-5l3hJazG8BoLZ0QxfSFc98uKArIGAFD1P8D6tsKMRt4="

[[manifest.projects]]
name = "hal_adi"
url = "https://github.com/zephyrproject-rtos/hal_adi"
revision = "a3eecfde1c76d38312b94fd346c7ba9fe2661992"
path = "modules/hal/adi"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-pau6AeJjaM8hTQZLE0kG/cQd2SHrwc5KgZHKPmV6Dq0="

[[manifest.projects]]
name = "hal_altera"
url = "https://github.com/zephyrproject-rtos/hal_altera"
revision = "4fe4df959d4593ce66e676aeba0b57f546dba0fe"
path = "modules/hal/altera"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-KM89pVzBbYatHtOtDq9EtBGpMp6rYcrKrXWHExKeqYM="

[[manifest.projects]]
name = "hal_ambiq"
url = "https://github.com/zephyrproject-rtos/hal_ambiq"
revision = "d3092f9b82874a1791baa3ac41c3795d108fbbdb"
path = "modules/hal/ambiq"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-MwKvY6S7UeRokpZSM2DFkiLX5rA0ymJeEdj3oH1paG8="

[[manifest.projects]]
name = "hal_atmel"
url = "https://github.com/zephyrproject-rtos/hal_atmel"
revision = "56d60ebc909ad065bf6554cee73487969857614b"
path = "modules/hal/atmel"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-axwXPNITDqPDccjs6oUpAvVZwFkMpM/bkEv6TVYcvo0="

[[manifest.projects]]
name = "hal_ethos_u"
url = "https://github.com/zephyrproject-rtos/hal_ethos_u"
revision = "8e2cf756b474eff9a32a9bdf1775d9620f1eadcf"
path = "modules/hal/ethos_u"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-VTkEDWTELMNka+naIUv4zkQqJEcJvYMEztgoWOlgDCA="

[[manifest.projects]]
name = "hal_gigadevice"
url = "https://github.com/zephyrproject-rtos/hal_gigadevice"
revision = "2994b7dde8b0b0fa9b9c0ccb13474b6a486cddc3"
path = "modules/hal/gigadevice"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-Cgcc+7tJy0ryQG4ynrlv7OmNe3OW2kMx1mStGROgA5o="

[[manifest.projects]]
name = "hal_infineon"
url = "https://github.com/zephyrproject-rtos/hal_infineon"
revision = "88d2529a3c5aee2e81947553bf6cbacb4671088c"
path = "modules/hal/infineon"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-xpui0+fujUXK4I136i8EJxQ4/GXhM1Y7s8aVkA22kuY="

[[manifest.projects]]
name = "hal_intel"
url = "https://github.com/zephyrproject-rtos/hal_intel"
revision = "8876a1815bc59e0464d285459b71e3d69872edfd"
path = "modules/hal/intel"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-g9dro+wszh4MIxGBGRtycWuQ4h4AU9iGLrbZMUDda7A="

[[manifest.projects]]
name = "hal_microchip"
url = "https://github.com/zephyrproject-rtos/hal_microchip"
revision = "71eba057c0cb7fc11b6f33eb40a82f1ebe2c571c"
path = "modules/hal/microchip"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-qtbwdJHUe3aDSffBIxwFA9sya7ETRUrBMNeOFRZjXWw="

[[manifest.projects]]
name = "hal_nordic"
url = "https://github.com/zephyrproject-rtos/hal_nordic"
revision = "cb7600a1be4c8b177867e6d463729c07dd3f6d73"
path = "modules/hal/nordic"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-cTT8hUKtXEEBUN7MCooqptJsxiZKz32vMvnKPrZCptI="

[[manifest.projects]]
name = "hal_nuvoton"
url = "https://github.com/zephyrproject-rtos/hal_nuvoton"
revision = "466c3eed9c98453fb23953bf0e0427fea01924be"
path = "modules/hal/nuvoton"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-0T+E4JUtSiWsypVPYnlRvDNr1otXRzLDCvx2TDQKS1Y="

[[manifest.projects]]
name = "hal_nxp"
url = "https://github.com/zephyrproject-rtos/hal_nxp"
revision = "4a4741fa2be33f6b638a49e357c5e33bb7ad0544"
path = "modules/hal/nxp"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-XYlBqiXrDYoPtUdxNrJBbiLfBTxyes6h3v0/yzdRaZI="

[[manifest.projects]]
name = "hal_openisa"
url = "https://github.com/zephyrproject-rtos/hal_openisa"
revision = "eabd530a64d71de91d907bad257cd61aacf607bc"
path = "modules/hal/openisa"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-krI/9sr57ZjerDKb9lQvIOD+q6vfiXqRGqV7cbW9Bqs="

[[manifest.projects]]
name = "hal_quicklogic"
url = "https://github.com/zephyrproject-rtos/hal_quicklogic"
revision = "bad894440fe72c814864798c8e3a76d13edffb6c"
path = "modules/hal/quicklogic"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-EFeySS+Kz7RecJ7it5CVAdP0y9m2gCCGl0Pu6l21+TQ="

[[manifest.projects]]
name = "hal_renesas"
url = "https://github.com/zephyrproject-rtos/hal_renesas"
revision = "3dafd030046f8d6f8a26080e9b9c1bcc92d45999"
path = "modules/hal/renesas"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-ClGJGR0re5N7cDPvMZ5z3StmETxK5jiwP3VQNMvvKkw="

[[manifest.projects]]
name = "hal_rpi_pico"
url = "https://github.com/zephyrproject-rtos/hal_rpi_pico"
revision = "79ee0f9e058a6327fc943d2f2a19cf3ade107cec"
path = "modules/hal/rpi_pico"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-WlEtwlpbDApZKjubf6ijjN48sxQbNdUMq8KQ2LihPvA="

[[manifest.projects]]
name = "hal_silabs"
url = "https://github.com/zephyrproject-rtos/hal_silabs"
revision = "69a5fad41aced94dc59d3103edd6ef370851e623"
path = "modules/hal/silabs"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-7t7VZzbJ+UlXHrhuFhxtrAcEb8EqBXq84zyg3U+x6IY="

[[manifest.projects]]
name = "hal_st"
url = "https://github.com/zephyrproject-rtos/hal_st"
revision = "b2f548fe672f24122c7f92027b2c9eeea8a0483a"
path = "modules/hal/st"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-ZVDYTzukYN/k5I6otwwHh3k9zBNI90vq1DXnCY75wcQ="

[[manifest.projects]]
name = "hal_stm32"
url = "https://github.com/zephyrproject-rtos/hal_stm32"
revision = "019d8255333f96bdd47d26b44049bd3e7af8ef55"
path = "modules/hal/stm32"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-pb5dUVsNH0Ym7t/xgP133lByE8+d1crSDk46qt0xLPs="

[[manifest.projects]]
name = "hal_telink"
url = "https://github.com/zephyrproject-rtos/hal_telink"
revision = "4226c7fc17d5a34e557d026d428fc766191a0800"
path = "modules/hal/telink"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-QBOMtj95FNrJ9q9/dwmCG5Ro22jgxVq6J7OUuwsaXmI="

[[manifest.projects]]
name = "hal_ti"
url = "https://github.com/zephyrproject-rtos/hal_ti"
revision = "2e7b95ad079e9f636884eedc6853e6ad98b85f65"
path = "modules/hal/ti"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-Oe4/VFMahMusnl8HZDmhfREOeYSLW+EJhqnNEOafnUg="

[[manifest.projects]]
name = "hal_wurthelektronik"
url = "https://github.com/zephyrproject-rtos/hal_wurthelektronik"
revision = "e3e2797b224fc48fdef1bc3e5a12a7c73108bba2"
path = "modules/hal/wurthelektronik"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-Xf/xazKK3ttGV7hdvUQanust2AUGjDyt62h1yl1Sc7A="

[[manifest.projects]]
name = "hal_xtensa"
url = "https://github.com/zephyrproject-rtos/hal_xtensa"
revision = "baa56aa3e119b5aae43d16f9b2d2c8112e052871"
path = "modules/hal/xtensa"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-GSSznCIBNt9y/MG4UGa0U9gn/oOr8C9K35WY1vccXas="

[[manifest.projects]]
name = "libmetal"
url = "https://github.com/zephyrproject-rtos/libmetal"
revision = "a6851ba6dba8c9e87d00c42f171a822f7a29639b"
path = "modules/hal/libmetal"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-TvJ8XiIa05lAUDfaGObkEuOjOUn3EzHPDxEVCoeiRBA="

[[manifest.projects]]
name = "liblc3"
url = "https://github.com/zephyrproject-rtos/liblc3"
revision = "1a5938ebaca4f13fe79ce074f5dee079783aa29f"
path = "modules/lib/liblc3"

[manifest.projects.nix]
hash = "sha256-nQJgF/cWoCx5TkX4xOaLB9SzvhVXPY29bLh7UwPMWEE="

[[manifest.projects]]
name = "littlefs"
url = "https://github.com/zephyrproject-rtos/littlefs"
revision = "009bcff0ed4853a53df8256039fa815bda6854dd"
path = "modules/fs/littlefs"
groups = ["fs"]

[manifest.projects.nix]
hash = "sha256-IKGJZGnw9EjIdwSYrYuCVO5J4cbDhPY5/DFNK7BLtM0="

[[manifest.projects]]
name = "loramac-node"
url = "https://github.com/zephyrproject-rtos/loramac-node"
revision = "fb00b383072518c918e2258b0916c996f2d4eebe"
path = "modules/lib/loramac-node"

[manifest.projects.nix]
hash = "sha256-mzvH8wh+si6q0QCoPl/mAm0QI3PkXGY3uaOMkimQtqg="

[[manifest.projects]]
name = "lvgl"
url = "https://github.com/zephyrproject-rtos/lvgl"
revision = "2b498e6f36d6b82ae1da12c8b7742e318624ecf5"
path = "modules/lib/gui/lvgl"

[manifest.projects.nix]
hash = "sha256-esrGS2Mz7RnT91O/wvMwxhtRemf7aq2iNAApCNonkCU="

[[manifest.projects]]
name = "mbedtls"
url = "https://github.com/zephyrproject-rtos/mbedtls"
revision = "a78176c6ff0733ba08018cba4447bd3f20de7978"
path = "modules/crypto/mbedtls"
groups = ["crypto"]

[manifest.projects.nix]
hash = "sha256-KSGhVbW2J0ndnGCiWh9ebnPd8OIfwg/Y3GlLvNylymQ="

[[manifest.projects]]
name = "mcuboot"
url = "https://github.com/zephyrproject-rtos/mcuboot"
revision = "f74b77cf7808919837c0ed14c2ead3918c546349"
path = "bootloader/mcuboot"
groups = ["bootloader"]

[manifest.projects.nix]
hash = "sha256-NGIylrc3UNUwyirADIjA73n4hwYButi+lwOfe4ZFaTs="

[[manifest.projects]]
name = "mipi-sys-t"
url = "https://github.com/zephyrproject-rtos/mipi-sys-t"
revision = "71ace1f5caa03e56c8740a09863e685efb4b2360"
path = "modules/debug/mipi-sys-t"
groups = ["debug"]

[manifest.projects.nix]
hash = "sha256-9Ps3igspEKar258fU2GbLRE17zyifFyGQ/2hF+lfL4w="

[[manifest.projects]]
name = "net-tools"
url = "https://github.com/zephyrproject-rtos/net-tools"
revision = "93acc8bac4661e74e695eb1aea94c7c5262db2e2"
path = "tools/net-tools"
groups = ["tools"]

[manifest.projects.nix]
hash = "sha256-Bst/K21L+NhYzq0icjBdd8Rj4vIOtjJTx7vSvzZlFzk="

[[manifest.projects]]
name = "open-amp"
url = "https://github.com/zephyrproject-rtos/open-amp"
revision = "b735edbc739ad59156eb55bb8ce2583d74537719"
path = "modules/lib/open-amp"

[manifest.projects.nix]
hash = "sha256-aockxz6wtvH0mOpkeiebOOIma1JDwdqkxT/N18/Jgqc="

[[manifest.projects]]
name = "openthread"
url = "https://github.com/zephyrproject-rtos/openthread"
revision = "2aeb8b833ba760ec29d5f340dd1ce7bcb61c5d56"
path = "modules/lib/openthread"

[manifest.projects.nix]
hash = "sha256-3t2P1VVvFxk2qMyjTDJlQNER9PKr+1fkdiYHAZlrucY="

[[manifest.projects]]
name = "picolibc"
url = "https://github.com/zephyrproject-rtos/picolibc"
revision = "d492d5fa7c96918e37653f303028346bb0dd51a2"
path = "modules/lib/picolibc"

[manifest.projects.nix]
hash = "sha256-5PHPmu6YIRIUtkDDq3g45e/HEN+bVZJyye8z287Xycc="

[[manifest.projects]]
name = "segger"
url = "https://github.com/zephyrproject-rtos/segger"
revision = "b011c45b585e097d95d9cf93edf4f2e01588d3cd"
path = "modules/debug/segger"
groups = ["debug"]

[manifest.projects.nix]
hash = "sha256-otxrP9Z4fUlJvdQ52jIXz9Bb6Fy3mr/jEFx9lhz0QlE="

[[manifest.projects]]
name = "tinycrypt"
url = "https://github.com/zephyrproject-rtos/tinycrypt"
revision = "1012a3ebee18c15ede5efc8332ee2fc37817670f"
path = "modules/crypto/tinycrypt"
groups = ["crypto"]

[manifest.projects.nix]
hash = "sha256-JQmkN+ircGU5Ald1+Q4lysuxhZLg2mJpNQ92+agMoCQ="

[[manifest.projects]]
name = "trusted-firmware-m"
url = "https://github.com/zephyrproject-rtos/trusted-firmware-m"
revision = "a11cd27905aecc4416cfc85552bfc3b997375056"
path = "modules/tee/tf-m/trusted-firmware-m"
groups = ["tee"]

[manifest.projects.nix]
hash = "sha256-6hFyTHEcGp81SNiakHnz467GnHSKQ/eN8I3TQdqIF5E="

[[manifest.projects]]
name = "trusted-firmware-a"
url = "https://github.com/zephyrproject-rtos/trusted-firmware-a"
revision = "713ffbf96c5bcbdeab757423f10f73eb304eff07"
path = "modules/tee/tf-a/trusted-firmware-a"
groups = ["tee"]

[manifest.projects.nix]
hash = "sha256-Dx+/fBHS7LabDu8mzfewdLdhoxVl5NO271V2EJZ+Y7g="

[manifest.self]
path = "bridle"
west-commands = "scripts/west-commands.yml"
