# The west manifest file for Li-Pro.Net bridle to embedded environment.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  # require west 9
  version: 0.9

  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/lipro-zephyr
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  # Please add items below based on alphabetical order
  projects:
    - name: zephyr
      path: zephyr
      remote: zephyrproject
      repo-path: zephyr
      revision: zephyr-v2.5.0
      clone-depth: 1
      # import submodules from zephyr manifest
      import:
        name-whitelist:
          - cmsis
          - hal_altera
          - hal_espressif
          - hal_stm32
          - hal_xtensa
          - net-tools
          - canopennode
      # import build commands from zephyr repo
      west-commands: scripts/west-commands.yml

  self:
    path: bridle
