# SPDX-FileCopyrightText: Copyright (c) 2026 TiaC Systems
# SPDX-License-Identifier: Apache-2.0

# display API on top of an LED strip matrix
# zephyr-keep-sorted-start
CONFIG_DISPLAY=y
CONFIG_LED_STRIP=y
# zephyr-keep-sorted-stop

# console output and logging
# zephyr-keep-sorted-start
CONFIG_BOOT_BANNER=y
CONFIG_LOG=y
CONFIG_PRINTK=y
# zephyr-keep-sorted-stop
