# Copyright (c) 2026 TiaC Systems
# SPDX-License-Identifier: Apache-2.0
"""The provenance banner every emitted artifact carries.

Its own module for one structural reason: overlay.py, sheet.py and
expectations.py all need it, and the emitter package imports all three.
Holding it in `emitter/__init__.py` therefore forced the package to
assign the banner and only THEN import its own submodules -- a genuine
import cycle (pylint R0401) that also put five imports below module
level (ruff E402). A leaf module both the package and its submodules can
import kills both, and leaves one definition, which was always the
point: three comment syntaxes carry this text (`/* */` in the overlay
and the includes file, `<!-- -->` in the config sheet, `#` in
expectations.yml) and none of them may drift from the others.
"""

from __future__ import annotations

#: Read by overlay.py, sheet.py and expectations.py; re-exported from the
#: package, which is where the test suite and any future caller name it.
GEN = "generated by rigc — do not edit; the rig file is the source of truth"
