/*
 * Copyright (c) 2023-2024 TiaC Systems
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef BRIDLE_INCLUDE_DT_BINDINGS_SEEED_GROVE_PWMS_DEFAULTS_H_
#define BRIDLE_INCLUDE_DT_BINDINGS_SEEED_GROVE_PWMS_DEFAULTS_H_

#include <zephyr/dt-bindings/dt-util.h>

#define __PWM_PINCTRL(x)	GROVE_PWM_##x##_PINCTRL
#define __PWM_ENABLE(x)		GROVE_PWM_##x##_ENABLE
#define __PWM_FAST(x)		GROVE_PWM_##x##_FAST
#define __PWM_SLOW(x)		GROVE_PWM_##x##_SLOW

#define GROVE_PWMS_SETUP_AND_ENABLE(port, kind)		\
	MACRO_MAP_CAT_N(1, __PWM_PINCTRL, port)		\
	MACRO_MAP_CAT_N(1, __PWM_ENABLE, port)		\
	MACRO_MAP_CAT_N(1, __PWM_##kind, port)

#define GROVE_PWM_D0_FAST	EMPTY
#define GROVE_PWM_D0_SLOW	EMPTY
#define GROVE_PWM_D0_ENABLE	EMPTY
#define GROVE_PWM_D0_PINCTRL	EMPTY

#define GROVE_PWM_D1_FAST	EMPTY
#define GROVE_PWM_D1_SLOW	EMPTY
#define GROVE_PWM_D1_ENABLE	EMPTY
#define GROVE_PWM_D1_PINCTRL	EMPTY

#define GROVE_PWM_D2_FAST	EMPTY
#define GROVE_PWM_D2_SLOW	EMPTY
#define GROVE_PWM_D2_ENABLE	EMPTY
#define GROVE_PWM_D2_PINCTRL	EMPTY

#define GROVE_PWM_D3_FAST	EMPTY
#define GROVE_PWM_D3_SLOW	EMPTY
#define GROVE_PWM_D3_ENABLE	EMPTY
#define GROVE_PWM_D3_PINCTRL	EMPTY

#define GROVE_PWM_D4_FAST	EMPTY
#define GROVE_PWM_D4_SLOW	EMPTY
#define GROVE_PWM_D4_ENABLE	EMPTY
#define GROVE_PWM_D4_PINCTRL	EMPTY

#define GROVE_PWM_D5_FAST	EMPTY
#define GROVE_PWM_D5_SLOW	EMPTY
#define GROVE_PWM_D5_ENABLE	EMPTY
#define GROVE_PWM_D5_PINCTRL	EMPTY

#define GROVE_PWM_D6_FAST	EMPTY
#define GROVE_PWM_D6_SLOW	EMPTY
#define GROVE_PWM_D6_ENABLE	EMPTY
#define GROVE_PWM_D6_PINCTRL	EMPTY

#define GROVE_PWM_D7_FAST	EMPTY
#define GROVE_PWM_D7_SLOW	EMPTY
#define GROVE_PWM_D7_ENABLE	EMPTY
#define GROVE_PWM_D7_PINCTRL	EMPTY

#define GROVE_PWM_D8_FAST	EMPTY
#define GROVE_PWM_D8_SLOW	EMPTY
#define GROVE_PWM_D8_ENABLE	EMPTY
#define GROVE_PWM_D8_PINCTRL	EMPTY

#define GROVE_PWM_D9_FAST	EMPTY
#define GROVE_PWM_D9_SLOW	EMPTY
#define GROVE_PWM_D9_ENABLE	EMPTY
#define GROVE_PWM_D9_PINCTRL	EMPTY

#define GROVE_PWM_D10_FAST	EMPTY
#define GROVE_PWM_D10_SLOW	EMPTY
#define GROVE_PWM_D10_ENABLE	EMPTY
#define GROVE_PWM_D10_PINCTRL	EMPTY

#define GROVE_PWM_D11_FAST	EMPTY
#define GROVE_PWM_D11_SLOW	EMPTY
#define GROVE_PWM_D11_ENABLE	EMPTY
#define GROVE_PWM_D11_PINCTRL	EMPTY

#define GROVE_PWM_D12_FAST	EMPTY
#define GROVE_PWM_D12_SLOW	EMPTY
#define GROVE_PWM_D12_ENABLE	EMPTY
#define GROVE_PWM_D12_PINCTRL	EMPTY

#define GROVE_PWM_D13_FAST	EMPTY
#define GROVE_PWM_D13_SLOW	EMPTY
#define GROVE_PWM_D13_ENABLE	EMPTY
#define GROVE_PWM_D13_PINCTRL	EMPTY

#define GROVE_PWM_D14_FAST	EMPTY
#define GROVE_PWM_D14_SLOW	EMPTY
#define GROVE_PWM_D14_ENABLE	EMPTY
#define GROVE_PWM_D14_PINCTRL	EMPTY

#define GROVE_PWM_D15_FAST	EMPTY
#define GROVE_PWM_D15_SLOW	EMPTY
#define GROVE_PWM_D15_ENABLE	EMPTY
#define GROVE_PWM_D15_PINCTRL	EMPTY

#define GROVE_PWM_D16_FAST	EMPTY
#define GROVE_PWM_D16_SLOW	EMPTY
#define GROVE_PWM_D16_ENABLE	EMPTY
#define GROVE_PWM_D16_PINCTRL	EMPTY

#define GROVE_PWM_D17_FAST	EMPTY
#define GROVE_PWM_D17_SLOW	EMPTY
#define GROVE_PWM_D17_ENABLE	EMPTY
#define GROVE_PWM_D17_PINCTRL	EMPTY

#define GROVE_PWM_D18_FAST	EMPTY
#define GROVE_PWM_D18_SLOW	EMPTY
#define GROVE_PWM_D18_ENABLE	EMPTY
#define GROVE_PWM_D18_PINCTRL	EMPTY

#define GROVE_PWM_D19_FAST	EMPTY
#define GROVE_PWM_D19_SLOW	EMPTY
#define GROVE_PWM_D19_ENABLE	EMPTY
#define GROVE_PWM_D19_PINCTRL	EMPTY

#define GROVE_PWM_D20_FAST	EMPTY
#define GROVE_PWM_D20_SLOW	EMPTY
#define GROVE_PWM_D20_ENABLE	EMPTY
#define GROVE_PWM_D20_PINCTRL	EMPTY

#define GROVE_PWM_D21_FAST	EMPTY
#define GROVE_PWM_D21_SLOW	EMPTY
#define GROVE_PWM_D21_ENABLE	EMPTY
#define GROVE_PWM_D21_PINCTRL	EMPTY

#define GROVE_PWM_D22_FAST	EMPTY
#define GROVE_PWM_D22_SLOW	EMPTY
#define GROVE_PWM_D22_ENABLE	EMPTY
#define GROVE_PWM_D22_PINCTRL	EMPTY

#define GROVE_PWM_D23_FAST	EMPTY
#define GROVE_PWM_D23_SLOW	EMPTY
#define GROVE_PWM_D23_ENABLE	EMPTY
#define GROVE_PWM_D23_PINCTRL	EMPTY

#define GROVE_PWM_D24_FAST	EMPTY
#define GROVE_PWM_D24_SLOW	EMPTY
#define GROVE_PWM_D24_ENABLE	EMPTY
#define GROVE_PWM_D24_PINCTRL	EMPTY

#define GROVE_PWM_D25_FAST	EMPTY
#define GROVE_PWM_D25_SLOW	EMPTY
#define GROVE_PWM_D25_ENABLE	EMPTY
#define GROVE_PWM_D25_PINCTRL	EMPTY

#define GROVE_PWM_D26_FAST	EMPTY
#define GROVE_PWM_D26_SLOW	EMPTY
#define GROVE_PWM_D26_ENABLE	EMPTY
#define GROVE_PWM_D26_PINCTRL	EMPTY

#define GROVE_PWM_D27_FAST	EMPTY
#define GROVE_PWM_D27_SLOW	EMPTY
#define GROVE_PWM_D27_ENABLE	EMPTY
#define GROVE_PWM_D27_PINCTRL	EMPTY

#define GROVE_PWM_D28_FAST	EMPTY
#define GROVE_PWM_D28_SLOW	EMPTY
#define GROVE_PWM_D28_ENABLE	EMPTY
#define GROVE_PWM_D28_PINCTRL	EMPTY

#define GROVE_PWM_D29_FAST	EMPTY
#define GROVE_PWM_D29_SLOW	EMPTY
#define GROVE_PWM_D29_ENABLE	EMPTY
#define GROVE_PWM_D29_PINCTRL	EMPTY

#define GROVE_PWM_D30_FAST	EMPTY
#define GROVE_PWM_D30_SLOW	EMPTY
#define GROVE_PWM_D30_ENABLE	EMPTY
#define GROVE_PWM_D30_PINCTRL	EMPTY

#define GROVE_PWM_D31_FAST	EMPTY
#define GROVE_PWM_D31_SLOW	EMPTY
#define GROVE_PWM_D31_ENABLE	EMPTY
#define GROVE_PWM_D31_PINCTRL	EMPTY

#endif /* BRIDLE_INCLUDE_DT_BINDINGS_SEEED_GROVE_PWMS_DEFAULTS_H_ */
