# Copyright (c) 2021-2025 TiaC Systems
# SPDX-License-Identifier: Apache-2.0

name: QA Conflict Finder and Labeler

on:
  push:
    branches-ignore:
      - '**'

jobs:
  qa-conflict:
    name: Run merge conflicts finder on patch series (PR)
    runs-on: ubuntu-24.04

    steps:
      - name: Run conflict finder and labeler
        uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: "has conflicts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
